#ifndef RESTAPIREQUESTS_GLOBAL_H
#define RESTAPIREQUESTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RESTAPIREQUESTS_LIBRARY)
#define RESTAPIREQUESTS_EXPORT Q_DECL_EXPORT
#else
#define RESTAPIREQUESTS_EXPORT Q_DECL_IMPORT
#endif

#endif // RESTAPIREQUESTS_GLOBAL_H
